### ISSUE TITLE
Performance of Bulk RNA-Seq

### ISSUE THREAD

**Issue by haessar** [Squalomix/utr-modeling#1]
Hi, I'm the developer of peaks2utr. Thanks for using my tool, and nice analysis.

Was curious how the Bulk RNA-Seq (outlined in section 4.2) performed in the end? (I assume this relates to the following issue https://github.com/haessar/peaks2utr/issues/21). I have't seen many use cases for bulk rather than single cell read data, so its interesting to know as a reference.

**Comment by Squalomix** [comment]
Hi. Thank you very much for your reaction. For the species we have tested (mainly medaka), peaks2utr works well with bulk RNA-seq data, which is confirmed with our computational check with the agat program package and manual inspection in JBrowse.

**Comment by haessar** [comment]
Good to hear!
